spring:
  application:
    name: GreenMate
  profiles:
    include:
      - database
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB
  cloud:
    compatibility-verifier:
      enabled: false
  threads:
    virtual:
      enabled: true
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

server:
  forward-headers-strategy: framework
  error:
    whitelabel:
      enabled: false
  shutdown: graceful

springdoc:
  swagger-ui:
    tagsSorter: alpha
    enabled: true
  api-docs:
    path: /api-docs
